{...}: {
  imports = [
    ./autopairs.nix
    ./colorizer.nix
    ./comment.nix
    ./conform.nix
    ./copilot.nix
    ./gitsigns.nix
    ./image.nix
    ./leap.nix
    ./lualine.nix
    ./luasnip.nix
    ./nvim-cmp.nix
    ./nvim-lspconfig.nix
    ./nvim-sops.nix
    ./nvim-tree.nix
    ./obsidian.nix
    ./oil.nix
    ./symbols-outline.nix
    ./telescope.nix
    ./theme-everforest.nix
    ./theme-github-light.nix
    ./theme-nightcity-kabuki.nix
    ./theme-onedark.nix
    ./toggleterm.nix
    ./treesitter.nix
    ./undotree.nix
    ./vim-fugitive.nix
  ];
}
