---
keys:
  - &primary age185kanaq3uw2gjx5enu2v69nk9ner3lamdevrfgx3wqucsl9ewa2qlt2gf7
creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
    - age:
      - *primary
  - path_regex: secrets/.*
    key_groups:
    - age:
      - *primary
      
