{...}: {
  imports = [
    ./anki.nix
    ./bitwarden.nix
    ./calibre.nix
    ./cura-appimage.nix
    ./darktable.nix
    ./dragon-drop.nix
    ./fastfetch.nix
    ./git.nix
    ./homeAutomation.nix
    ./k9s.nix
    ./kitty.nix
    ./kubetools.nix
    ./lf.nix
    ./libreoffice.nix
    ./mpv.nix
    ./ncmpcpp.nix
    ./obsidian.nix
    ./picard.nix
    ./plexamp.nix
    ./signal.nix
    ./tmux.nix
    ./tmuxSessioniser.nix
    ./vimiv.nix
    ./webcord.nix
    ./zathura.nix
    ./zsh.nix
  ];
}
