name: update-flakes
"on":
  schedule:
    - cron: 20 4 * * 0,2,4,6
  workflow_dispatch: null

jobs:
  update-flakes:
    runs-on: ubuntu-latest
    steps:
      - uses: jlumbroso/free-disk-space@v1.3.1
        with:
          swap-storage: false
          tool-cache: true
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |-
            accept-flake-config = true
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v16
        with:
          authToken: ${{ secrets.CACHIX_TOKEN }}
          extraPullNames: nix-community
          name: lucidph3nx-nixos-config
      - name: Update flake.lock
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          nix flake update --commit-lock-file
      - name: 'Build NixOS configs for: navi, default and tui'
        run: |-
          nix build --print-build-logs '.#nixosConfigurations.navi.config.system.build.toplevel'
          nix build --print-build-logs '.#nixosConfigurations.default.config.system.build.toplevel'
          nix build --print-build-logs '.#nixosConfigurations.tui.config.system.build.toplevel'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          body: |
            ## Run report

            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          branch: flake-updates
          delete-branch: true
          title: Update flake.lock
